apiVersion: v1
kind: Secret
metadata:
  name: campuscart-secret
  namespace: campuscart
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: campuscart
  MYSQL_USER: campus
  MYSQL_PASSWORD: campus123
  DB_USER: campus
  DB_PASSWORD: campus123
